openapi: 3.0.0
info:
  title: Open API
  description: OpenApi description
  version: 1.0.0

servers:
  - url: http://laravel9-playground.com/api
    description: 本地

  - url: https://development.com/api
    description: 測試區

paths:
  /articles:
    get:
      tags:
        - Articles
      operationId: getArticles
      summary: 取得文章列表
      description: 取得文章列表
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
